package pixformer.model.sound;

import java.util.LinkedList;
import java.util.List;

import pixformer.model.entity.Entity;
import pixformer.model.entity.components.Component;

public abstract class SoundComponent extends Component<Entity> {

    private final List<SoundEvent> soundList;

    protected SoundComponent(Entity entity) {
        super(entity);
        soundList = new LinkedList<SoundEvent>();
    }

    /**
     * Add a sound to the sound list.
     * @param newAudio new entity sound.
     */
    protected void addSound(final SoundEvent newSound) {
        soundList.add(newSound);
    }

    /**
     * @return a list of sounds generated by the entity.
     */
    protected List<SoundEvent> getSounds() {
        List<SoundEvent> sounds = new LinkedList<SoundEvent>(soundList);
        clearSoundList();
        return sounds;
    }

    /**
     * Clear current sound list.
     */
    protected void clearSoundList() {
        this.soundList.clear();
    }
}
