package pixformer.model.sound;

import java.util.List;

/**
 * Represent an entity that can reproduce sounds.
 */
public interface Soundable {
    /**
     * Add a sound to the sound list.
     * @param newAudio new entity sound.
     */
    void addSound(final SoundEvent newSound);

    /**
     * @return a list of sounds generated by the entity.
     */
    List<SoundEvent> getSounds();

    /**
     * Clear current sound list.
     */
    default void clearSoundList() {
        this.getSounds().clear();
    }
}
