package pixformer.model.sound;

import java.util.LinkedList;
import java.util.List;

import pixformer.model.entity.Entity;
import pixformer.model.entity.components.Component;

/**
 * Represents the component that manages the sound of entities.
 */
public abstract class SoundComponent extends Component<Entity> {

    private final List<SoundEvent> soundList;

    /**
     * @param entity linked to the Soundcomponent.
     */
    protected SoundComponent(final Entity entity) {
        super(entity);
        soundList = new LinkedList<>();
    }

    /**
     * Add a sound to the sound list.
     * @param newSound new entity sound.
     */
    protected void addSound(final SoundEvent newSound) {
        soundList.add(newSound);
    }

    /**
     * @return a list of sounds generated by the entity.
     */
    public List<SoundEvent> getSounds() {
        final List<SoundEvent> sounds = new LinkedList<>(soundList);
        clearSoundList();
        return sounds;
    }

    /**
     * Clear current sound list.
     */
    protected void clearSoundList() {
        this.soundList.clear();
    }
}
